language: node_js
node_js:
  - "node"
  - "6"
install:
  - "npm install -g @angular/cli"
  - npm install
  - "npm install @angular/core@4 @angular/forms@4"
script:
  - npm run build
  - npm run test:once
