language: node_js
node_js:
  - "node"
  - "6"
install:
  - "npm install -g @angular/cli"
  - npm install
script:
  - npm run build
  - npm run test:once
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: docs
  on:
    branch: master
