language: node_js
node_js:
  - "node"
  - "6"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - "npm install -g @angular/cli"
  - npm install
  - "npm install @angular/core@4 @angular/forms@4"
script:
  - npm run build
  - npm run test:once
