language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- node
- '6'
env:
- NG_VERSION=4 TS_VERSION=2.3.4 MAT_VERSION=2.0.0-beta.12 CLI_VERSION=1.6.1 RX_VERSION=5.0.1
  RAMDA_VERSION=0.25.0 MOMENT_VERSION=2.19
- NG_VERSION=5 TS_VERSION=2.4.2 MAT_VERSION=5 CLI_VERSION=1.7.4 RX_VERSION=5.5.6 RAMDA_VERSION=0.25.0
  MOMENT_VERSION=2.19
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g @angular/cli@${CLI_VERSION}
- npm install rxjs@${RX_VERSION} ramda@${RAMDA_VERSION} typescript@${TS_VERSION} moment@${MOMENT_VERSION}
- npm install @angular/common@${NG_VERSION} @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}
- npm install @angular/http@${NG_VERSION} @angular/platform-browser@${NG_VERSION}
  @angular/platform-browser-dynamic@${NG_VERSION}
- npm install @angular/compiler@${NG_VERSION} @angular/compiler-cli@${NG_VERSION}
- npm install @angular/animations@${NG_VERSION} @angular/cdk@${MAT_VERSION} @angular/material@${MAT_VERSION}
- npm install
script:
- npm run build
- npm run test:once
before_deploy:
- cd lib
deploy:
  skip_cleanup: true
  provider: npm
  email: tigredonorte3@gmail.com
  on:
    repo: tigredonorte/angular-date-format
    branch: develop
  api_key:
    secure: DjXGop/ahkGFU+gXJ1QKOXi0+fwg1suraqE2PPt1SLG9jpI2kEWHQnFXS0yymQWFZ+Cz8FR6c53ShIY8+w/2YBnHFSVjDe8o+AUIQf4A0qZ2744/xlMND5DXUcyJu2LViiFQ7qgFL3I1lBFp6CCBuy7GtOh/mWMgwlZ6XUh/e6zaoJPg02gzwu3Gq+QBz3cClcR2KpVMYxqZMgfSRIxRGIyfdfvYv8qbp/sxXfpEDiijyKX3y50qOqCzPPV/+bwE9d4EyasuSip9Tl3z0qjCZdpelEdguoMRgqDg2GFHydtK7rsr1bJ+a5oVxzWjbSiOrtBlaQFi/CUFS2NR6SsYZpmhDSTGnR2IOT3tQg7EtvYwD+7XL4Y744+iWDm62faI/OS2hEW+7gEg5/Jhr87auSOXyWelXeR4I3UPJm3rLsNV9azHIccOOmJBbQzgNLAmjCLaHv7nmtC+PRe61m8PJyXrbedcq+vqntX3IUqzwqtNNogTGuhefbTZi6nv3T2lt1jVg6A8Vt5j9dMv3A3bkkrYpfq0WHkTW9VssCCfbHsdHgCod7kbXqrAbC0m7iz0yToUCTv9O31ra2ZhPR7DxTl+5RIzWssGW+3gzsmBu9J12+BP2f2LaLFGPdbt5FeT6q3KZceJVGykXjv2AeF5CRxUb/nG8P0uBFA61QG0Y7A=
