language: node_js

node_js:
  - "node"
  - "6"

env:
  - NG_VERSION=2
  - NG_VERSION=4
  - NG_VERSION=5

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - "npm install -g @angular/cli"
  - npm install
  - "npm install @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}"

script:
  - npm run build
  - npm run test:once
