language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- node
- '6'
env:
- NG_VERSION=4 TS_VERSION=2.3.4 MAT_VERSION=2.0.0-beta.12 CLI_VERSION=1.6.1 RX_VERSION=5.0.1
  RAMDA_VERSION=0.25.0 MOMENT_VERSION=2.19
- NG_VERSION=5 TS_VERSION=2.4.2 MAT_VERSION=5 CLI_VERSION=1.7.4 RX_VERSION=5.5.6 RAMDA_VERSION=0.25.0
  MOMENT_VERSION=2.19
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g @angular/cli@${CLI_VERSION}
- npm install rxjs@${RX_VERSION} ramda@${RAMDA_VERSION} typescript@${TS_VERSION} moment@${MOMENT_VERSION}
- npm install @angular/common@${NG_VERSION} @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}
- npm install @angular/http@${NG_VERSION} @angular/platform-browser@${NG_VERSION}
  @angular/platform-browser-dynamic@${NG_VERSION}
- npm install @angular/compiler@${NG_VERSION} @angular/compiler-cli@${NG_VERSION}
- npm install @angular/animations@${NG_VERSION} @angular/cdk@${MAT_VERSION} @angular/material@${MAT_VERSION}
- npm install
script:
- npm run build
- npm run test:once
before_deploy:
- "{ sed -nE 's/^[ \\t]*\"version\": \"([0-9]{1,}\\.[0-9]{1,}\\.)[0-9x]{1,}\",$/\\1/p' package.json; git describe --abbrev=0 | sed -E 's/^v([0-9]{1,}\\.[0-9]{1,}\\.)([0-9]{1,})$/\\1 \\2/g'; } | tr \"\\n\" \" \" | awk '{printf($1==$2?\"v\"$2$3+1:\"v\"$1$3\")}' | xargs -I {} git tag -a {} -m \"{}\"\n"
- cd dist
deploy:
- provider: npm
  skip_cleanup: true
  email: tigredonorte3@gmail.com
  on:
    repo: gorilainvest/angular-date-format
    branch: master
  api_key:
    secure: CuBfB6Cp1mlGJou7PyBWgzJlPz5MNEbhl6kK3QSCs6mDfwZafe3PZ2hrqRgJZ7CVmHQZIc4+0ZU7/g84DpDvIRTnN/hHt8dnLOrLSGCtgdm9Cycf8hgpYNBOEezxO+t89fzTE05izmoABVlL1743XyURqpqMmhOCirruh2tBk+l5rh00VonsKdvZJUR4CYlSOkGRa6EoZbgiR33VP7U6NVJKNd3JHetxEE4Oh6EjMW8c6w360q0Kz9wS38v3z7Cu0rSZ/ps7lS+XDjeUvS/dMrSHZrX9rGtYS1fiigQyCnuoVxeadBpjylpMM7d2pMf1ciMmdoU/5ONN+/IvZUXPx2AcXGpYSExay3jpV1HcHqhYKiVlaRcnBpN3x7h9h2VtqAoLnVUP3ekpp++99bQey1t16IfzZpv+R2CGwWnW8btStwuQ8LptmGwxMttkI0Iu5jpx5ApdFcv3WgQ/8Qmm6mN4luyip28ltA1qvskHIyLsnz5RqCqUZxKpa8OGCgDY68Uzs7OcWcTlPRsFP8OTBt18q2cpezo7XXoRP0MkgJh+iLdtefo8OJ2QWJE9G7tu/2RZFoVHO1W0aYRikrz8rPgMaQwGDNMr1KBMcX1DcDw9G60r2AOWWsVNk3/enyADYzFfHZhLMa+PCFtOT1URU8nVv2NGD+qpNj+BYMbxWqc=
