language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- node
- '6'
env:
- NG_VERSION=4 TS_VERSION=2.3.4 MAT_VERSION=2.0.0-beta.12 CLI_VERSION=1.6.1 RX_VERSION=5.0.1
  RAMDA_VERSION=0.25.0 MOMENT_VERSION=2.19
- NG_VERSION=5 TS_VERSION=2.4.2 MAT_VERSION=5 CLI_VERSION=1.7.4 RX_VERSION=5.5.6 RAMDA_VERSION=0.25.0
  MOMENT_VERSION=2.19
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g @angular/cli@${CLI_VERSION}
- npm install rxjs@${RX_VERSION} ramda@${RAMDA_VERSION} typescript@${TS_VERSION} moment@${MOMENT_VERSION}
- npm install @angular/common@${NG_VERSION} @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}
- npm install @angular/http@${NG_VERSION} @angular/platform-browser@${NG_VERSION}
  @angular/platform-browser-dynamic@${NG_VERSION}
- npm install @angular/compiler@${NG_VERSION} @angular/compiler-cli@${NG_VERSION}
- npm install @angular/animations@${NG_VERSION} @angular/cdk@${MAT_VERSION} @angular/material@${MAT_VERSION}
- npm install
script:
- npm run build
- npm run test:once
before_deploy:
- cd dist
deploy:
  provider: npm
  skip_cleanup: true
  email: it+github@gorilainvest.com.br
  on:
    repo: gorilainvest/angular-date-format
    tags: true
  api_key:
    secure: aVGe1+bL73X0gEw0jhBFoIquB96q4b3Bs8H4TTDFMBJpZbwu3hi0Glb7VlfLk+I4rXoV4QwrY4iaDn54gCxQiv0vHH9jAKlkQJhMHewmn1tN+KyIdy9R3OCVXBfVp7oss2Y/aFHj0FrmY5pWiTnN96ja+P/OwBt/sfe4KKppwyUSyK2QZx9iI5t/Lvow+mgc2o013nJdFnWV/oRVDbqGIP/aLrLmovC9p2xDem0Yi7fMxtWRuw+kAfxBGmGpuZ9f2YBVuBcT1YUbNMimXta+Rjx8uy2GEGszhF8Dg6wGhByE/gzuynx/cT8NiTMr477aTfHizxEp4TuHExruI1RcQZYKp59/jIfFD0XheeB9yDqQ0DnMjjOkDcRQQtVNwwqwBTZZzlMF2cae0UvwjJxzBh3oxa2t1A/XBfarom9PfrvX2cIOJSPASIA3cQnCwqvyhb93NcfDoBZLJh294BCwe7k4PFCEbi1N5IdPm80t3v3XYZ22TLiSdN+9w/gXhd9PQH+oEGQ60G8YKG6LcJbWNd85NbmkxUJqJbc+5rLNm9xedDQHfAjYpsO/7hweYkC8wG6pbCUcW/FB2mtUa5dMRXeTLsvxpQtOmbccpRAuSjLv4CD33W96zKdCtP/Dsglc1M2ZVCPjqNd9BnuGtDV5jZ+UzjGou3wHkNmcKno9rAs=
